spring:
  application:
    name=task-tracker-backend

  datasource:
    url: "jdbc:postgresql://localhost:5432/task_tracker_db"
    username: "postgres"
    password: "123"


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


jwt:
  secret: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
  lifetime: 30m


server:
  port: 8080